### ISSUE TITLE
Ability for users to change prefix

### ISSUE THREAD

**Issue by eduardo-olivares1** [eduardo-olivares1/Narwhal#5]
Some users may not like a fixed prefix, especially those who already have a number of bots in their server(s)

Command could look like the following: 
`
$narwhalPrefix <new_prefix>
`

Should definitely start with changing 
`
const prefix = "$"; 
`
To
`
let prefix = "$"; 
`

Default prefix could still be "$" ...

**Comment by fredtsun** [comment]
Would this be per user or a global prefix change?

**Comment by eduardo-olivares1** [comment]
This would be a global prefix change. All users in a server would be able to change the prefix for their instance of the bot.

**Comment by eduardo-olivares1** [comment]
Feature added in #10
